<?php

// autoload_static.php @generated by Mozart

namespace Composer\Autoload;

class MozartStaticInit14f9cb4bd8f43095590940f0cb84e387
{
    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'ScriptReport\\Vendor\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ScriptReport\\Vendor\\' =>
        array (
            0 => __DIR__ . '/..',
        ),
    );

    public static $classMap = array (
        'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Telemetry' => __DIR__ . '/../BitApps/WPTelemetry/Telemetry/Telemetry.php',
        'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\TelemetryConfig' => __DIR__ . '/../BitApps/WPTelemetry/Telemetry/TelemetryConfig.php',
        'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Feedback\\Feedback' => __DIR__ . '/../BitApps/WPTelemetry/Telemetry/Feedback/Feedback.php',
        'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Report\\ReportInfo' => __DIR__ . '/../BitApps/WPTelemetry/Telemetry/Report/ReportInfo.php',
        'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Report\\Report' => __DIR__ . '/../BitApps/WPTelemetry/Telemetry/Report/Report.php',
    );


    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = MozartStaticInit14f9cb4bd8f43095590940f0cb84e387::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = MozartStaticInit14f9cb4bd8f43095590940f0cb84e387::$prefixDirsPsr4;
            $loader->classMap = MozartStaticInit14f9cb4bd8f43095590940f0cb84e387::$classMap;
        }, null, ClassLoader::class);
    }
}
