<?php

// autoload_real.php @generated by Mozart

class MozartAutoloaderInit14f9cb4bd8f43095590940f0cb84e387
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('MozartAutoloaderInit14f9cb4bd8f43095590940f0cb84e387', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('MozartAutoloaderInit14f9cb4bd8f43095590940f0cb84e387', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\MozartStaticInit14f9cb4bd8f43095590940f0cb84e387::getInitializer($loader));

        $loader->register(true);


        return $loader;
    }
}
