<?php

// autoload_classmap.php @generated by Mozart

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir, 1);

return array(
    'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Telemetry' => $vendorDir . '/BitApps/WPTelemetry/Telemetry/Telemetry.php',
    'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\TelemetryConfig' => $vendorDir . '/BitApps/WPTelemetry/Telemetry/TelemetryConfig.php',
    'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Feedback\\Feedback' => $vendorDir . '/BitApps/WPTelemetry/Telemetry/Feedback/Feedback.php',
    'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Report\\ReportInfo' => $vendorDir . '/BitApps/WPTelemetry/Telemetry/Report/ReportInfo.php',
    'ScriptReport\\Vendor\\BitApps\\WPTelemetry\\Telemetry\\Report\\Report' => $vendorDir . '/BitApps/WPTelemetry/Telemetry/Report/Report.php',
);
